CREATE TABLE IF NOT EXISTS `leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lead_code` VARCHAR(50) NOT NULL UNIQUE,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL,
  `company` VARCHAR(200) NULL,
  `position` VARCHAR(100) NULL,
  `source` VARCHAR(50) NOT NULL,
  `source_detail` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'medium',
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `assigned_to` INT NULL,
  `assigned_at` DATETIME NULL,
  `score` INT NULL DEFAULT 0,
  `converted` BOOLEAN NOT NULL DEFAULT FALSE,
  `converted_at` DATETIME NULL,
  `converted_amount` DECIMAL(10,2) NULL,
  `converted_customer_id` INT NULL,
  `closed` BOOLEAN NOT NULL DEFAULT FALSE,
  `closed_at` DATETIME NULL,
  `close_reason` VARCHAR(200) NULL,
  `created_by` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_lead_code` (`lead_code`),
  INDEX `idx_phone` (`phone`),
  INDEX `idx_email` (`email`),
  INDEX `idx_status` (`status`),
  INDEX `idx_assigned_to` (`assigned_to`),
  INDEX `idx_converted` (`converted`),
  INDEX `idx_converted_customer_id` (`converted_customer_id`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_created_at` (`created_at`),
  CONSTRAINT `fk_leads_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_leads_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_leads_converted_customer_id` FOREIGN KEY (`converted_customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
